// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11_HK9brFyfqTXNhU_L29k6pQp7bVAo0',
    appId: '1:673675625174:web:75bf445c8019086f71ff77',
    messagingSenderId: '673675625174',
    projectId: 'myproject-c54c4',
    authDomain: 'myproject-c54c4.firebaseapp.com',
    storageBucket: 'myproject-c54c4.appspot.com',
    measurementId: 'G-WWKLNF4XG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyUpxojj7VJNGYr8DJKH6xqry5FlIY9E',
    appId: '1:673675625174:android:9192ec67d0555a5271ff77',
    messagingSenderId: '673675625174',
    projectId: 'myproject-c54c4',
    storageBucket: 'myproject-c54c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lxGTPmNHBdJZuxLS1zag8snM6dI0Yg8',
    appId: '1:673675625174:ios:b538f7df2830ce6d71ff77',
    messagingSenderId: '673675625174',
    projectId: 'myproject-c54c4',
    storageBucket: 'myproject-c54c4.appspot.com',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lxGTPmNHBdJZuxLS1zag8snM6dI0Yg8',
    appId: '1:673675625174:ios:6ec9046032bfcace71ff77',
    messagingSenderId: '673675625174',
    projectId: 'myproject-c54c4',
    storageBucket: 'myproject-c54c4.appspot.com',
    iosBundleId: 'com.example.ap.RunnerTests',
  );
}
